// inertia/components/Sidebar.tsx
import { useState } from 'react'
import { Link, router } from '@inertiajs/react'
import {
  Calendar,
  LayoutDashboard,
  Menu,
  EllipsisVertical,
  X as CloseIcon,
  Hash,
  MessageSquare,
  Settings,
  Moon,
  Sun,
  Users,
} from 'lucide-react'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from './ui/dropdown-menu'
import { Button } from './ui/button'
import ThemeToggle from './ThemeToggle'

interface SidebarProps {
  user: any
  account?: {
    id: string
    handle: string
    followersCount?: number
  }
}

function Sidebar({ user, account }: SidebarProps) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)

  // Get current path
  const currentPath = typeof window !== 'undefined' ? window.location.pathname : ''

  async function handleLogout() {
    await router.put('/logout')
  }

  async function handleDeleteAccount() {
    if (confirm('Are you sure you want to delete your account? This action is irreversible.')) {
      await router.delete('/delete')
    }
  }

  function isActive(href: string): boolean {
    if (href === '/') {
      return currentPath === '/' || currentPath === ''
    }
    return currentPath.startsWith(href)
  }

  return (
    <>
      {!isSidebarOpen && (
        <button
          className="md:hidden fixed top-4 left-4 z-50 p-2 bg-background/80 backdrop-blur border border-border rounded-md shadow-sm"
          onClick={() => setIsSidebarOpen(true)}
        >
          <Menu className="h-5 w-5 text-foreground/80" />
        </button>
      )}

      {/* Sidebar */}
      <aside
        className={`fixed inset-y-0 left-0 z-50 w-64 bg-card/80 backdrop-blur-md border-r border-border/50 shadow-sm transform transition-transform duration-300 ease-in-out md:translate-x-0 flex flex-col overflow-hidden ${
          isSidebarOpen ? 'translate-x-0' : '-translate-x-full'
        }`}
      >
        {/* Bouton de fermeture (visible sur mobile) */}
        <button
          className="absolute top-4 right-4 md:hidden p-2 rounded-full hover:bg-background/80 transition-colors"
          onClick={() => setIsSidebarOpen(false)}
        >
          <CloseIcon className="h-5 w-5 text-foreground/70" />
        </button>

        <div className="p-4 flex items-center gap-3 flex-shrink-0 border-b border-border/30">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-full bg-blue-600 dark:bg-blue-500 flex items-center justify-center text-white font-bold text-lg shadow-sm">
              B
            </div>
            <span className="text-xl font-bold text-blue-600 dark:text-blue-400">Bluesky Bot</span>
          </Link>
        </div>

        <nav className="px-3 py-4 flex-1 overflow-y-auto">
          <div className="space-y-1.5">
            <Link
              href="/dashboard"
              className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 ${
                isActive('/dashboard')
                  ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
                  : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'
              }`}
            >
              <LayoutDashboard className="h-[18px] w-[18px] flex-shrink-0" />
              Dashboard
            </Link>

            <Link
              href="/schedule"
              className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 ${
                isActive('/schedule')
                  ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
                  : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'
              }`}
            >
              <Calendar className="h-[18px] w-[18px] flex-shrink-0 text-current" />
              Scheduling
            </Link>

            <Link
              href="/feeds"
              className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 ${
                isActive('/feeds')
                  ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
                  : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'
              }`}
            >
              <Hash className="h-[18px] w-[18px] flex-shrink-0" />
              Feeds
            </Link>

            <Link
              href="/dm-campaigns"
              className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 ${
                isActive('/dm-campaigns')
                  ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
                  : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'
              }`}
            >
              <MessageSquare className="h-[18px] w-[18px] flex-shrink-0" />
              DM Campaigns
            </Link>

            <Link
              href="/follower-tracker"
              className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 ${
                isActive('/follower-tracker')
                  ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
                  : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'
              }`}
            >
              <Users className="h-[18px] w-[18px] flex-shrink-0" />
              Follower Tracker
            </Link>
          </div>

          {/* Current Account Info */}
          {account && (
            <div className="mt-6 px-3">
              <div className="border-t border-border/30 pt-4">
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                  Current Account
                </p>
                <div className="flex items-center gap-3 p-2 rounded-md bg-accent/30">
                  <div className="w-8 h-8 rounded-full bg-blue-600 dark:bg-blue-500 flex items-center justify-center text-white font-semibold text-sm">
                    {account.handle[0]?.toUpperCase() || 'A'}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-foreground truncate">
                      @{account.handle}
                    </p>
                    {account.followersCount !== undefined && (
                      <p className="text-xs text-muted-foreground">
                        {account.followersCount.toLocaleString()} followers
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
        </nav>

        {/* Footer with user info */}
        <div className="p-3 border-t border-border/30 flex-shrink-0">
          <div className="flex items-center gap-3">
            {/* Avatar with better contrast */}
            <div className="relative">
              <div className="w-9 h-9 rounded-full bg-blue-600 dark:bg-blue-500 flex items-center justify-center text-white font-semibold text-sm shadow-lg ring-2 ring-white/20 dark:ring-white/10">
                {user?.email?.[0]?.toUpperCase() || 'U'}
              </div>
              <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-green-500 rounded-full border-2 border-background"></div>
            </div>

            {/* User info */}
            <div className="min-w-0 flex-1">
              <div className="text-sm font-semibold text-foreground truncate">
                {user?.email?.split('@')[0] || 'User'}
              </div>
              <div className="text-xs text-muted-foreground truncate">
                {user?.subscription?.plan || 'Free'} Plan
              </div>
            </div>

            {/* Dropdown menu */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className="w-8 h-8 p-0 hover:bg-accent/80 transition-colors"
                >
                  <EllipsisVertical className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <div className="px-2 py-1.5 text-sm text-muted-foreground">
                  {user?.email || 'user@example.com'}
                </div>
                <DropdownMenuSeparator />

                {/* Theme toggle integrated in menu */}
                <DropdownMenuItem onClick={(e) => e.preventDefault()}>
                  <div className="flex items-center justify-between w-full">
                    <span className="flex items-center">
                      {typeof window !== 'undefined' &&
                      document.documentElement.className === 'dark' ? (
                        <Moon className="h-4 w-4 mr-2" />
                      ) : (
                        <Sun className="h-4 w-4 mr-2" />
                      )}
                      Theme
                    </span>
                    <ThemeToggle />
                  </div>
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem asChild>
                  <Link href="/profile" className="flex items-center">
                    <Settings className="h-4 w-4 mr-2" />
                    Settings
                  </Link>
                </DropdownMenuItem>

                <DropdownMenuItem asChild>
                  <Link href="/plan/change" className="flex items-center">
                    <span className="mr-2">✨</span>
                    {user?.plan === 'pro' ? 'Manage Plan' : 'Upgrade Plan'}
                  </Link>
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem onClick={handleLogout}>
                  <div className="flex items-center text-amber-600 dark:text-amber-500">
                    <svg
                      className="h-4 w-4 mr-2"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"
                      />
                    </svg>
                    Logout
                  </div>
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem
                  onClick={handleDeleteAccount}
                  className="text-destructive focus:text-destructive"
                >
                  <svg
                    className="h-4 w-4 mr-2"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
                    />
                  </svg>
                  Delete Account
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </aside>

      {/* Overlay pour mobile */}
      {isSidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 md:hidden"
          onClick={() => setIsSidebarOpen(false)}
        />
      )}
    </>
  )
}

export default Sidebar

// inertia/lib/components/Sidebar.svelte
<script lang="ts">
  import type User from '#models/user'
  import {
    Calendar,
    LayoutDashboard,
    Menu,
    EllipsisVertical,
    X as CloseIcon,
    Hash,
    MessageSquare,
    Settings,
  } from 'lucide-svelte'
  import { router } from '@inertiajs/svelte'
  import {
    DropdownMenu,
    DropdownMenuTrigger,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
  } from '@/shadcn-ui/dropdown-menu'
  import Button from '@/shadcn-ui/button/button.svelte'
  import ThemeToggle from '@/components/theme-toggle/theme-toggle.svelte'
  import { page } from '@inertiajs/svelte'

  export let user: User

  let isSidebarOpen = false
  let path = $page.url

  async function handleLogout() {
    await router.put('/logout')
  }

  async function handleDeleteAccount() {
    if (confirm('Are you sure you want to delete your account? This action is irreversible.')) {
      await router.delete('/delete')
    }
  }

  function isActive(href: string): boolean {
    // Cas spécial pour la page d'accueil
    if (href === '/') {
      return path === '/' || path === ''
    }
    // Pour les autres pages
    return path.startsWith(href)
  }
</script>

{#if !isSidebarOpen}
  <button
    class="md:hidden fixed top-4 left-4 z-50 p-2 bg-background/80 backdrop-blur border border-border rounded-md shadow-sm"
    on:click={() => (isSidebarOpen = true)}
  >
    <Menu class="h-5 w-5 text-foreground/80" />
  </button>
{/if}

<!-- Sidebar -->
<aside
  class="fixed inset-y-0 left-0 z-50 w-64 bg-card/80 backdrop-blur-md border-r border-border/50 shadow-sm transform transition-transform duration-300 ease-in-out md:translate-x-0 flex flex-col overflow-hidden sidebar-main"
  class:translate-x-0={isSidebarOpen}
  class:-translate-x-full={!isSidebarOpen}
>
  <!-- Bouton de fermeture (visible sur mobile) -->
  <button
    class="absolute top-4 right-4 md:hidden p-2 rounded-full hover:bg-background/80 transition-colors"
    on:click={() => (isSidebarOpen = false)}
  >
    <CloseIcon class="h-5 w-5 text-foreground/70" />
  </button>

  <div class="p-4 flex items-center gap-3 flex-shrink-0 border-b border-border/30">
    <a href="/" class="flex items-center gap-3">
      <div
        class="w-9 h-9 rounded-full bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center text-white font-bold text-lg shadow-sm"
      >
        B
      </div>
      <span
        class="text-xl font-bold bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent"
      >
        Bluesky Bot
      </span>
    </a>
  </div>

  <nav class="px-3 py-4 flex-1 overflow-y-auto scrollbar-thin">
    <div class="space-y-1.5">
      <a
        href="/dashboard"
        class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 {isActive(
          '/dashboard'
        )
          ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
          : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'}"
      >
        <LayoutDashboard class="h-[18px] w-[18px] flex-shrink-0" />
        Dashboard
      </a>
      <a
        href="/feed"
        class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 {isActive(
          '/feed'
        )
          ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
          : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'}"
      >
        <Hash class="h-[18px] w-[18px] flex-shrink-0" />
        Feeds
      </a>
      <a
        href="/schedule"
        class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 {isActive(
          '/schedule'
        )
          ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
          : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'}"
      >
        <Calendar class="h-[18px] w-[18px] flex-shrink-0" />
        Scheduling
      </a>
      <a
        href="/DM_Campaigns"
        class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 {isActive(
          '/DM_Campaigns'
        )
          ? 'bg-blue-500/10 text-blue-950 dark:text-blue-500 font-semibold shadow-sm'
          : 'text-blue-950 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-900 dark:hover:text-blue-500 font-medium'}"
      >
        <MessageSquare class="h-[18px] w-[18px] flex-shrink-0" />
        DM Campaigns
      </a>
    </div>

    {#if user?.plan === 'pro'}
      <div class="mt-8">
        <div class="px-3 mb-2">
          <p
            class="text-xs font-semibold text-purple-700 dark:text-purple-400 uppercase tracking-wider"
          >
            Pro Features
          </p>
          <div class="h-0.5 w-8 bg-purple-500 rounded mt-1"></div>
        </div>
        <div class="space-y-1.5">
          <a
            href="/AiPost"
            class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-all duration-150 {isActive(
              '/AiPost'
            )
              ? 'bg-blue-500/10 text-blue-700 dark:text-blue-500 font-semibold shadow-sm'
              : 'text-blue-700 dark:text-blue-400 hover:bg-accent/50 hover:text-blue-700 dark:hover:text-blue-500 font-medium'}"
          >
            <span
              class="flex h-[18px] w-[18px] items-center justify-center rounded-full bg-blue-500 text-[9px] font-bold text-white"
            >
              AI
            </span>
            AI Posts
          </a>
        </div>
      </div>
    {/if}
  </nav>

  <!-- Section utilisateur avec menu dropdown -->
  {#if user}
    <div
      class="p-4 border-t border-border/30 flex flex-col gap-2 flex-shrink-0 bg-card/60 backdrop-blur-sm"
    >
      <div class="flex items-center gap-3">
        <div
          class="w-9 h-9 rounded-full bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shadow-sm"
        >
          <span class="text-sm font-bold text-blue-700 dark:text-blue-500"
            >{user.email[0].toUpperCase()}</span
          >
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm font-semibold truncate text-blue-700 dark:text-blue-500">
            {user.email}
          </p>
          <p
            class="text-xs font-medium text-blue-600 dark:text-blue-400 truncate flex items-center"
          >
            <span
              class="inline-block w-2 h-2 rounded-full {user.plan === 'pro'
                ? 'bg-blue-500'
                : 'bg-gray-400'} mr-1.5"
            ></span>
            {user.plan === 'pro' ? 'Pro' : 'Free'} Plan
          </p>
        </div>

        <!-- Menu déroulant -->
        <DropdownMenu>
          <DropdownMenuTrigger asChild let:builder>
            <Button
              class="p-2 rounded-md hover:bg-accent bg-background/0"
              variant="ghost"
              size="icon"
              builders={[builder]}
            >
              <EllipsisVertical class="h-5 w-5" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" class="w-56">
            <DropdownMenuItem href="/profile">
              <Settings class="mr-2 h-4 w-4" />
              Settings
            </DropdownMenuItem>
            <DropdownMenuItem href="/plan/change">
              <span class="mr-2">✨</span>
              Upgrade Plan
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem on:click={handleLogout}>Logout</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              class="text-destructive focus:text-destructive"
              on:click={handleDeleteAccount}
            >
              Delete Account
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div class="flex items-center justify-between mt-2 pt-2 border-t border-border/20">
        <span class="text-sm font-medium text-blue-700 dark:text-blue-400">Theme</span>
        <ThemeToggle />
      </div>
    </div>
  {/if}
</aside>

<style>
  :global(.sidebar-main) {
    width: 16rem; /* 64px / 4px = 16rem in tailwind */
  }

  @media (max-width: 768px) {
    :global(.sidebar-main) {
      width: 16rem;
    }
  }
</style>
