// inertia/pages/planChange.svelte
<script lang="ts">
  import { page, router } from '@inertiajs/svelte'
  import Button from '@/ui/button/button.svelte'
  import { Card, CardContent, CardHeader, CardTitle } from '@/ui/card'
  import { Gem, Zap, CheckCircle, ChevronRight } from 'lucide-svelte'
  import Sidebar from '@/components/Sidebar.svelte'
  import type User from '#models/user'

  let user: User = $page.props.user
  $: isFreePlan = user.plan === 'free'
  $: isProPlan = user.plan === 'pro'
</script>

<main class="flex md:flex-row min-h-screen">
  <div class="h-screen">
    <Sidebar {user} />
  </div>

  <div class="flex flex-col w-full flex-2 overflow-hidden pt-6 px-12">
    <header class="flex gap-4 md:py-6">
      <div class="flex flex-col w-full">
        <div class="space-y-1 text-left">
          <h1 class="text-3xl font-bold">Account Plan</h1>
          <p class="text-sm text-gray-400">Manage your subscription and usage</p>
        </div>
      </div>
    </header>

    <!-- Contenu principal -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 py-6 animate-fade-in-up">
      <!-- Carte Plan Actuel -->
      <Card class="hover:border-blue-400 transition-all duration-300 group relative">
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium text-gray-300">
            Current Plan
            {#if isProPlan}
              <span class="text-blue-400 text-xs ml-1">Active</span>
            {:else}
              <span class="text-gray-400 text-xs ml-1">Basic</span>
            {/if}
          </CardTitle>
          <div class="relative p-2 bg-gradient-to-br from-blue-600 to-blue-400 rounded-lg">
            <Zap class="h-5 w-5 text-white" />
          </div>
        </CardHeader>

        <CardContent>
          <div class="text-3xl font-bold text-blue-400 mb-4">
            {user.plan.toUpperCase()}
          </div>

          {#if isFreePlan}
            <div class="space-y-3 text-sm">
              <div class="flex items-center gap-2 text-gray-300">
                <CheckCircle class="h-4 w-4 text-green-400" />
                <span>{user.dmsSent}/30 Free DMs per month</span>
              </div>
              <div class="flex items-center gap-2 text-gray-300">
                <CheckCircle class="h-4 w-4 text-green-400" />
                <span>Basic Automation</span>
              </div>
            </div>
          {:else}
            <div class="space-y-3 text-sm">
              <div class="flex items-center gap-2 text-gray-300">
                <CheckCircle class="h-4 w-4 text-green-400" />
                <span>Unlimited DMs</span>
              </div>
              <div class="flex items-center gap-2 text-gray-300">
                <CheckCircle class="h-4 w-4 text-green-400" />
                <span>Advanced Automation</span>
              </div>
              <div class="flex items-center gap-2 text-gray-300">
                <CheckCircle class="h-4 w-4 text-green-400" />
                <span>Priority Support</span>
              </div>
            </div>
          {/if}
        </CardContent>
      </Card>

      <!-- Carte Upgrade -->
      <Card class="hover:border-purple-400 transition-all duration-300 group relative">
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium text-gray-300">
            {isFreePlan ? 'Upgrade to Pro' : 'Manage Subscription'}
          </CardTitle>
          <div class="relative p-2 bg-gradient-to-br from-purple-600 to-purple-400 rounded-lg">
            <Gem class="h-5 w-5 text-white" />
          </div>
        </CardHeader>

        <CardContent>
          {#if isFreePlan}
            <div class="space-y-4">
              <div class="text-gray-300 text-sm">
                <p class="mb-3">Get full access to all Pro features:</p>
                <ul class="space-y-2">
                  <li class="flex items-center gap-2">
                    <ChevronRight class="h-4 w-4 text-purple-400" />
                    Unlimited Auto DMs
                  </li>
                  <li class="flex items-center gap-2">
                    <ChevronRight class="h-4 w-4 text-purple-400" />
                    Multiple Accounts
                  </li>
                  <li class="flex items-center gap-2">
                    <ChevronRight class="h-4 w-4 text-purple-400" />
                    Advanced Analytics
                  </li>
                </ul>
              </div>

              <Button
                on:click={async () => {
                  await router.post('/create-stripe-session')
                }}
                class="w-full mt-4 bg-purple-500 hover:bg-purple-400 transition-colors"
              >
                Upgrade to Pro - $4.99/mo
              </Button>
            </div>
          {:else}
            <div class="text-gray-300 text-sm space-y-4">
              <p>
                Your Pro subscription is active. Manage your billing information or downgrade to
                Free plan.
              </p>
              <Button
                on:click={async () => {
                  {
                    if (
                      !confirm(
                        'Are you sure you want to downgrade to Free plan? Your Pro features will be disabled immediately.'
                      )
                    )
                      return
                    await router.post('/downgrade-plan')
                  }
                }}
                class="w-full"
                variant="outline"
                color="red"
              >
                Downgrade to Free
              </Button>
            </div>
          {/if}
        </CardContent>
      </Card>
    </div>
  </div>
</main>

// inertia/pages/planChange.tsx
import { Head } from '@inertiajs/react'
import Layout from '../components/Layout'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card'
import { Button } from '../components/ui/button'
import { Badge } from '../components/ui/badge'
import { Check, Sparkles, Star, Zap } from 'lucide-react'

interface PlanChangeProps {
  user: any
}

function PlanChange({ user }: PlanChangeProps) {
  const currentPlan = user?.plan || 'free'

  return (
    <>
      <Head title="Upgrade Plan" />
      <Layout user={user}>
        <div className="p-6 max-w-6xl mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-foreground mb-2">Choose Your Plan</h1>
            <p className="text-muted-foreground">
              Unlock powerful features to grow your Bluesky presence
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {/* Free Plan */}
            <Card className={`relative ${currentPlan === 'free' ? 'ring-2 ring-blue-500' : ''}`}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Star className="h-5 w-5 text-gray-500" />
                    Free Plan
                  </CardTitle>
                  {currentPlan === 'free' && <Badge variant="secondary">Current</Badge>}
                </div>
                <div className="text-3xl font-bold">
                  $0<span className="text-lg font-normal text-muted-foreground">/month</span>
                </div>
                <p className="text-muted-foreground">Perfect for getting started</p>
              </CardHeader>
              <CardContent className="space-y-4">
                <ul className="space-y-3">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Up to 3 connected accounts</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Basic scheduling</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Simple analytics</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Community support</span>
                  </li>
                </ul>

                {currentPlan === 'free' ? (
                  <Button disabled className="w-full">
                    Current Plan
                  </Button>
                ) : (
                  <Button variant="outline" className="w-full">
                    Downgrade to Free
                  </Button>
                )}
              </CardContent>
            </Card>

            {/* Pro Plan */}
            <Card
              className={`relative ${currentPlan === 'pro' ? 'ring-2 ring-blue-500' : 'ring-2 ring-gradient-to-r from-purple-500 to-blue-500'}`}
            >
              <div className="absolute -top-2 left-1/2 transform -translate-x-1/2">
                <Badge className="bg-gradient-to-r from-purple-500 to-blue-500 text-white">
                  <Sparkles className="h-3 w-3 mr-1" />
                  Most Popular
                </Badge>
              </div>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Zap className="h-5 w-5 text-purple-500" />
                    Pro Plan
                  </CardTitle>
                  {currentPlan === 'pro' && <Badge variant="secondary">Current</Badge>}
                </div>
                <div className="text-3xl font-bold">
                  $29<span className="text-lg font-normal text-muted-foreground">/month</span>
                </div>
                <p className="text-muted-foreground">For serious content creators</p>
              </CardHeader>
              <CardContent className="space-y-4">
                <ul className="space-y-3">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Unlimited connected accounts</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Advanced scheduling & automation</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">AI-powered content suggestions</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Detailed analytics & insights</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Audience analysis</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">DM campaigns</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Priority support</span>
                  </li>
                </ul>

                {currentPlan === 'pro' ? (
                  <Button disabled className="w-full">
                    Current Plan
                  </Button>
                ) : (
                  <Button className="w-full bg-white dark:bg-gray-800 border-2 border-blue-200 dark:border-blue-700 text-blue-700 dark:text-blue-300 hover:bg-blue-50 dark:hover:bg-blue-900/20 hover:border-blue-300 dark:hover:border-blue-600 transition-all shadow-sm hover:shadow-md font-medium">
                    Upgrade to Pro
                  </Button>
                )}
              </CardContent>
            </Card>
          </div>

          {/* FAQ Section */}
          <div className="mt-12 max-w-3xl mx-auto">
            <h2 className="text-2xl font-bold text-center mb-6">Frequently Asked Questions</h2>
            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <h3 className="font-semibold">Can I change my plan anytime?</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Yes, you can upgrade or downgrade your plan at any time. Changes take effect
                    immediately, and you'll be billed prorated for upgrades.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <h3 className="font-semibold">What happens to my data if I downgrade?</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Your data remains safe. However, you'll lose access to Pro features and may need
                    to disconnect excess accounts if you exceed the Free plan limits.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <h3 className="font-semibold">Is there a refund policy?</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    We offer a 7-day money-back guarantee for new Pro subscriptions. Contact support
                    if you're not satisfied with your upgrade.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </Layout>
    </>
  )
}

export default PlanChange
