// inertia/pages/pricing.svelte
<script lang="ts">
  import LayoutLandingPage from '@/components/layoutLandingPage.svelte'
  import Button from '@/ui/button/button.svelte'
  import { Rocket, Sparkles, CheckCircle, X } from 'lucide-svelte'

  type PlanFeature = {
    text: string
    included: boolean
  }

  type Plan = {
    title: string
    price: string
    buttonText: string
    features: PlanFeature[]
    isHighlighted?: boolean
    limit?: string
  }

  const plans: Plan[] = [
    {
      title: 'Starter',
      price: 'Free',
      buttonText: 'Get Started',
      features: [
        { text: '30 automated DMs/month', included: true },
        { text: '5 scheduled posts at a time.', included: true },
        { text: 'Basic analytics dashboard', included: true },
        { text: 'Limited bot actions (auto-reply, follow-back)', included: true },
        { text: 'Community support', included: true },
        { text: 'Unlimited automated DMs', included: false },
        { text: 'Unlimited scheduled posts', included: false },
        { text: 'Massive DM campaigns', included: false },
      ],
    },
    {
      title: 'Pro',
      price: '$4.99/mo',
      buttonText: 'Upgrade to Pro',
      isHighlighted: true,
      features: [
        { text: 'Unlimited automated DMs', included: true },
        { text: 'Unlimited scheduled posts', included: true },
        { text: 'Massive DM campaigns', included: true },
        { text: 'Advanced analytics', included: true },
        { text: 'Full bot automation (auto-reply, follow-back, etc.)', included: true },
        { text: 'Priority support', included: true },
      ],
    },
  ]
</script>

<main class="min-h-screen">
  <LayoutLandingPage />

  <section id="pricing" class="relative pt-12">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2
          class="text-4xl font-bold mb-4 bg-gradient-to-r from-teal-400 to-blue-500 bg-clip-text text-transparent"
        >
          Simple Pricing for Early Innovators
        </h2>
        <p class="text-gray-400 text-xl max-w-2xl mx-auto">
          Start growing your Bluesky presence risk-free during our alpha phase
        </p>
      </div>

      <div class="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
        {#each plans as plan}
          <div
            class={`relative p-8 rounded-2xl transition-all duration-300 ${
              plan.isHighlighted
                ? 'border-2 border-teal-500/30 bg-gradient-to-br from-teal-900/20 to-blue-900/20 shadow-xl shadow-teal-500/10'
                : 'border border-gray-800 bg-gray-900/50 hover:border-gray-700'
            }`}
          >
            {#if plan.isHighlighted}
              <div
                class="absolute top-0 right-0 bg-teal-500 text-white px-4 py-1 rounded-bl-lg text-sm"
              >
                Limited Alpha
              </div>
            {/if}

            <div class="mb-6">
              <h3 class="text-2xl font-bold mb-2 flex items-center gap-2">
                {#if plan.isHighlighted}
                  <Rocket class="w-6 h-6 text-teal-400" />
                {:else}
                  <Sparkles class="w-6 h-6 text-blue-400" />
                {/if}
                {plan.title}
              </h3>
              <div class="text-3xl font-bold mb-4">
                {plan.price}
                {#if plan.limit}
                  <span class="block text-sm text-teal-400 mt-1">{plan.limit}</span>
                {/if}
              </div>
            </div>

            <ul class="space-y-3 mb-8">
              {#each plan.features as feature}
                <li class="flex items-start gap-3 text-gray-300">
                  {#if feature.included}
                    <CheckCircle class="w-5 h-5 text-teal-400 flex-shrink-0 mt-1" />
                  {:else}
                    <X class="w-5 h-5 text-red-400/80 flex-shrink-0 mt-1" />
                  {/if}
                  <span class={feature.included ? '' : 'text-gray-500'}>{feature.text}</span>
                </li>
              {/each}
            </ul>

            <div class="flex h-full">
              <Button
                variant="outline"
                class={`w-full py-4 mt-full text-lg ${
                  plan.isHighlighted
                    ? 'bg-gradient-to-r from-teal-500 to-blue-600 hover:from-teal-600 hover:to-blue-700'
                    : 'border-gray-700 text-gray-300 hover:border-blue-500'
                }`}
                href="/dashboard"
              >
                {plan.buttonText}
              </Button>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </section>
</main>

// inertia/pages/pricing.tsx
import { Head } from '@inertiajs/react'
import { Check, X } from 'lucide-react'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card'

function Pricing() {
  const plans = [
    {
      name: 'Free',
      price: '0',
      period: 'forever',
      description: 'Perfect for getting started',
      features: [
        '1 Bluesky account',
        '5 scheduled posts per month',
        'Basic analytics',
        'Community support',
      ],
      limitations: ['No advanced analytics', 'No bulk scheduling', 'No priority support'],
      buttonText: 'Get Started',
      buttonVariant: 'outline' as const,
      popular: false,
    },
    {
      name: 'Pro',
      price: '9',
      period: 'month',
      description: 'For growing creators and businesses',
      features: [
        '5 Bluesky accounts',
        'Unlimited scheduled posts',
        'Advanced analytics',
        'Audience insights',
        'Bulk scheduling',
        'Priority support',
      ],
      limitations: [],
      buttonText: 'Start Free Trial',
      buttonVariant: 'default' as const,
      popular: true,
    },
    {
      name: 'Enterprise',
      price: '29',
      period: 'month',
      description: 'For teams and agencies',
      features: [
        'Unlimited accounts',
        'Unlimited scheduled posts',
        'Advanced analytics',
        'Team collaboration',
        'White-label options',
        'Custom integrations',
        'Dedicated support',
      ],
      limitations: [],
      buttonText: 'Contact Sales',
      buttonVariant: 'outline' as const,
      popular: false,
    },
  ]

  return (
    <>
      <Head title="Pricing" />
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 dark:from-gray-900 dark:to-gray-800">
        <div className="container mx-auto px-4 py-16">
          {/* Header */}
          <div className="text-center mb-16">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-4">
              Simple, Transparent Pricing
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Choose the perfect plan for your Bluesky management needs. All plans include our core
              features with no hidden fees.
            </p>
          </div>

          {/* Pricing Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {plans.map((plan, index) => (
              <Card
                key={index}
                className={`relative transition-all duration-300 hover:shadow-xl ${
                  plan.popular ? 'border-blue-500 shadow-lg scale-105' : 'hover:scale-105'
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                    <span className="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-4 py-1 rounded-full text-sm font-medium">
                      Most Popular
                    </span>
                  </div>
                )}

                <CardHeader className="text-center pb-8">
                  <CardTitle className="text-2xl font-bold">{plan.name}</CardTitle>
                  <div className="mt-4">
                    <span className="text-4xl font-bold">${plan.price}</span>
                    <span className="text-muted-foreground">/{plan.period}</span>
                  </div>
                  <p className="text-muted-foreground mt-2">{plan.description}</p>
                </CardHeader>

                <CardContent className="space-y-6">
                  {/* Features */}
                  <div className="space-y-3">
                    {plan.features.map((feature, featureIndex) => (
                      <div key={featureIndex} className="flex items-center gap-3">
                        <Check className="h-4 w-4 text-green-500 flex-shrink-0" />
                        <span className="text-sm">{feature}</span>
                      </div>
                    ))}
                  </div>

                  {/* Limitations */}
                  {plan.limitations.length > 0 && (
                    <div className="space-y-3 pt-4 border-t">
                      {plan.limitations.map((limitation, limitIndex) => (
                        <div key={limitIndex} className="flex items-center gap-3">
                          <X className="h-4 w-4 text-red-400 flex-shrink-0" />
                          <span className="text-sm text-muted-foreground">{limitation}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* CTA Button */}
                  <div className="pt-6">
                    <Button variant={plan.buttonVariant} className="w-full" size="lg">
                      {plan.buttonText}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* FAQ Section */}
          <div className="mt-20 max-w-3xl mx-auto">
            <h2 className="text-2xl font-bold text-center mb-8">Frequently Asked Questions</h2>
            <div className="space-y-6">
              <Card>
                <CardContent className="p-6">
                  <h3 className="font-semibold mb-2">Can I change plans anytime?</h3>
                  <p className="text-muted-foreground">
                    Yes! You can upgrade or downgrade your plan at any time. Changes take effect
                    immediately and we'll prorate any differences.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-6">
                  <h3 className="font-semibold mb-2">Is there a free trial?</h3>
                  <p className="text-muted-foreground">
                    The Pro plan comes with a 14-day free trial. No credit card required to start.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-6">
                  <h3 className="font-semibold mb-2">What payment methods do you accept?</h3>
                  <p className="text-muted-foreground">
                    We accept all major credit cards (Visa, MasterCard, American Express) and PayPal
                    for your convenience.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* CTA Section */}
          <div className="text-center mt-16">
            <h2 className="text-2xl font-bold mb-4">Ready to get started?</h2>
            <p className="text-muted-foreground mb-6">
              Join thousands of creators who trust us with their Bluesky presence
            </p>
            <div className="flex gap-4 justify-center">
              <Button size="lg">Start Free Trial</Button>
              <Button variant="outline" size="lg" asChild>
                <a href="/contact-us">Contact Sales</a>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Pricing
