// inertia/svelte-back/components/theme-toggle/theme-toggle.svelte
<script lang="ts">
  import { Moon, Sun } from 'lucide-svelte'
  import { Button } from '@/shadcn-ui/button'
  import { theme } from '../../../stores/theme'
  import { onMount } from 'svelte'

  let mounted = false
  let currentTheme: 'light' | 'dark' = 'dark'

  onMount(() => {
    mounted = true
    const storedTheme = localStorage.getItem('theme') || 'dark'
    currentTheme = storedTheme as 'light' | 'dark'
    theme.setTheme(currentTheme)
  })

  function toggleTheme() {
    theme.toggleTheme()
    currentTheme = currentTheme === 'dark' ? 'light' : 'dark'
  }
</script>

{#if mounted}
  <Button
    variant="ghost"
    size="icon"
    class="w-9 px-0 rounded-full overflow-hidden relative"
    on:click={toggleTheme}
    aria-label={`Switch to ${currentTheme === 'dark' ? 'light' : 'dark'} theme`}
  >
    <div
      class="absolute inset-0 transition-all duration-500 ease-in-out bg-gradient-to-br {currentTheme ===
      'dark'
        ? 'from-indigo-900/10 to-purple-900/10 opacity-0'
        : 'from-amber-200/20 to-yellow-100/20 opacity-100'}"
    ></div>
    <Sun
      class="h-[1.2rem] w-[1.2rem] transition-all duration-500 {currentTheme === 'dark'
        ? 'rotate-90 scale-0 opacity-0'
        : 'rotate-0 scale-100 opacity-100'} text-amber-500"
    />
    <Moon
      class="absolute h-[1.2rem] w-[1.2rem] transition-all duration-500 {currentTheme === 'dark'
        ? 'rotate-0 scale-100 opacity-100'
        : 'rotate-90 scale-0 opacity-0'} text-indigo-400"
    />
  </Button>
{/if}

// inertia/components/ThemeToggle.tsx
import { useState, useEffect } from 'react'
import { Moon, Sun } from 'lucide-react'
import { Button } from './ui/button'

function ThemeToggle() {
  const [mounted, setMounted] = useState(false)
  const [currentTheme, setCurrentTheme] = useState<'light' | 'dark'>('dark')

  useEffect(() => {
    setMounted(true)
    const storedTheme = localStorage.getItem('theme') || 'dark'
    setCurrentTheme(storedTheme as 'light' | 'dark')
    document.documentElement.className = storedTheme
  }, [])

  function toggleTheme() {
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark'
    setCurrentTheme(newTheme)
    localStorage.setItem('theme', newTheme)
    document.documentElement.className = newTheme
  }

  if (!mounted) {
    return null
  }

  return (
    <Button
      variant="outline"
      size="sm"
      className="w-16 h-6 px-1 rounded-full border-border/50 hover:border-border transition-all duration-200"
      onClick={toggleTheme}
      aria-label={`Switch to ${currentTheme === 'dark' ? 'light' : 'dark'} theme`}
    >
      <div className="flex items-center justify-between w-full">
        <Sun
          className={`h-3 w-3 transition-all duration-300 ${
            currentTheme === 'dark' ? 'scale-75 opacity-40' : 'scale-100 opacity-100 text-amber-500'
          }`}
        />
        <Moon
          className={`h-3 w-3 transition-all duration-300 ${
            currentTheme === 'dark' ? 'scale-100 opacity-100 text-blue-400' : 'scale-75 opacity-40'
          }`}
        />
      </div>
    </Button>
  )
}

export default ThemeToggle
